# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12lX21iizKkc9pxatNwQy3Qekn6wI66mn
"""

from google.colab import drive
drive.mount('/content/drive')

from google.colab import drive
import os

# ✅ Mount Drive
drive.mount('/content/drive')

# ✅ Define full path to dataset
DATA_YAML_PATH = "/content/drive/MyDrive/Colab Notebooks/topcam12.v2i.yolov8/data/data.yaml"
dataset_root = "/content/drive/MyDrive/Colab Notebooks/topcam12.v2i.yolov8/data"

# ✅ Fix Roboflow-style paths in YAML
if os.path.exists(DATA_YAML_PATH):
    with open(DATA_YAML_PATH, "r") as f:
        content = f.read()

    content = content.replace("../train/images", f"{dataset_root}/train/images")
    content = content.replace("../valid/images", f"{dataset_root}/valid/images")
    content = content.replace("../test/images", f"{dataset_root}/test/images")

    with open(DATA_YAML_PATH, "w") as f:
        f.write(content)

    print("✅ data.yaml paths fixed.")
else:
    print("❌ data.yaml not found at expected path.")

!pip install ultralytics

from ultralytics import YOLO
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"🚀 Training on device: {device}")

model = YOLO("yolov8n.yaml")
model.train(
    data=DATA_YAML_PATH,
    epochs=30,
    imgsz=640,
    batch=16,
    device=device,
    name="missing_component_model"
)

from google.colab import files
files.download('runs/detect/missing_component_model2/weights/best.pt')